Make vc_packager ignore MacOS metadata files
educelab/volume-cartographer pull request #78
Opened 2024-02-27 14:42 UTC by TheCleric

Fixes #77

2024-02-27 15:48 UTC, csparker247 requested changes
Boost is slated for removal as a dependency (it's currently only used for program arguments), so this needs to be rewritten without Boost.String. We provide a `to_lower` implementation in `vc/core/utils/String.hpp`.

I also think it's sufficient to just have a simple `IsUnixHiddenFile` free function that checks if the filename begins with `.`. Probably doesn't even need the `to_lower` calls. Put it in  `vc/core/io/FileExtensionFilter.hpp` and I will maybe rename that header.

2024-02-27 22:12 UTC, TheCleric commented
@csparker247 I have done as you asked.

2024-02-28 01:09 UTC, csparker247 commented
Removed the `starts_with` function since we can just check the first character of the filename in this case. Also C++20 adds a `string::starts_with` function, so no need to implement it unless we _really_ need it. Also renamed `FileExtensionFilters.hpp` to `FileFilters.hpp`. 

Thanks for the bug report and contribution!

2024-02-28 01:12 UTC, csparker247 approved these changes

2024-02-28 01:39 UTC, merged